name: lint

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: npm install
      run: |
        npm install
      env:
        CI: true
    - name: lint
      run: |
        npm run lint
      env:
        CI: true